config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope "(:locale)", locale: /fr|en|it/ do
    get 'mentionslegales', to: 'pages#mentionslegales', as: 'mentionslegales'
    get 'services', to: 'pages#services', as: :services
    get 'realisations', to: 'pages#realisations', as: :realisations
    get 'contact', to: 'contacts#new', as: :contacts
    post 'contact', to: 'contacts#create'
    root to: 'pages#home'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
  :presence => :true,
  :format => {
    :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    :message => "Non valide"
  }
validates :message, :presence => :true
validates :name, :presence => :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
    { locale: I18n.locale }
  end

  # Make sure your production HOST variable is set with your domain name. If you deploy your code with Heroku for instance, just type in your terminal heroku config:set HOST=www.my_product.com
  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if verify_recaptcha(model: @contact) && @contact.save
      ContactMailer.general_message(@contact).deliver_now
      render :thanks
    else
      flash[:alert] = I18n.t 'errors.template.body'
      render :new
    end
  end

  def thanks
  end

private

  def contact_params
    params.require(:contact).permit(:email, :message, :name, :tel)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def realisations
  end

  def services
  end


  def mentionslegales
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div id="banner">
  <div class="navspace"></div>
  <h1><%= t(:contact_nous) %></h1>
  <%= render 'shared/form' %>

</div>

app/views/contacts/thanks.html.erb
<div id="banner">
  <div class="navspace"></div>
  <h1><%= t(:thanksmail) %></h1>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BOURDIEC 06 - Plombier / Couvreur / Zingueur </title>
    <meta name="description" content="Une équipe et un savoir-faire à votre service depuis 1976 sur Menton, Roquebrune Cap Martin et environs. Interventions chez les particuliers et dans les copropriétés. Devis gratuit.">
    <!-- Facebook card -->
    <meta property="og:title" content="BOURDIEC 06 - Plombier / Couvreur / Zingueur">
    <meta property="og:image" content="images/Banniere_bourdiec_06.png">
    <meta property="og:description" content="Une équipe et un savoir-faire à votre service depuis 1976 sur Menton, Roquebrune Cap Martin et environs. Interventions chez les particuliers et dans les copropriétés. Devis gratuit.">
    <meta property="og:site_name" content="Bourdiec06"/>
    <!-- Twitter card -->
<!--     <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@...">
    <meta name="twitter:title" content="BOURDIEC 06 - Plombier / Couvreur / Zingueur">
    <meta name="twitter:description" content="Une équipe et un savoir-faire à votre service depuis 1976 sur Menton, Roquebrune Cap Martin et environs.">
    <meta name="twitter:creator" content="@...">
    <meta name="twitter:image:src" content="images/Banniere_bourdiec_06.png"> -->
    <!-- link  -->
    <%= favicon_link_tag %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700%7COpen+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/3ae22cffc7.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/footerfooter' %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="banner" class="home">
  <!-- <div class="banner-content"> -->
    <%= image_tag "naming.png", alt:"logo", class:"logobanner" %>
    <p>Une équipe et un savoir-faire à votre service depuis 1976 sur Menton, Roquebrune Cap Martin et environs <br><br> Interventions chez les particuliers et dans les copropriétés <br><br> Devis gratuit</p>
  <!-- </div> -->
</div>

<div class="wrapper">
  <div class="container" id="plomb">
    <div class="flexbox">
      <div class="textcard">
        <h2><%= t(:plomberie) %></h2>
        <p><ul>
          <li>Recherche de fuite</li>
          <li>Dépannage, débouchage</li>
          <li>Réparation et rénovation de salle de bains, sanitaires et cuisines</li>
          <li>Remplacement de cumulus</li>
          <li>Réparation et réfection de canalisation d’eau enterrée, encastrée ou en façade</li>
          <li>Mise aux normes et remplacement de fosse septique</li>
        </ul></p>
      </div>
      <div class="imgcard">
        <%= cl_image_tag("Bourdiec06/plomberie.jpg", alt:"plomberie travaux", class:"imgimgcard") %>
      </div>
    </div>
  </div>
</div>
<div class="container" id="toit">
  <div class="flexbox2">
    <div class="imgcard">
      <%= cl_image_tag("Bourdiec06/toiture3", alt:"toiture neuve Menton", class:"imgimgcard") %>
    </div>
    <div class="textcardright">
      <h2><%= t(:couverture) %></h2>
      <p><ul>
        <li>Réfection de toitures en tuiles plates, romanes ou canal</li>
        <li>Recherche de fuite</li>
        <li>Intervention pour réparation en urgence</li>
        <li>Pose de Velux</li>
        <li>Pose d’isolation sous-toiture ou en comble</li>
        <li>Entretien, contrôle et nettoyage annuel de toiture</li>
      </ul></p>
    </div>
  </div>
</div>
<div class="wrapper">
  <div class="container" id="zing">
    <div class="flexbox">
      <div class="textcard">
        <h2><%= t(:zinguerie) %></h2>
        <p><ul>
          <li>Intervention en urgence sur zinguerie</li>
          <li>Réalisation de tous travaux en zinc et en plomb</li>
          <li>Réfection de gouttière, d'abergement de cheminée, de chéneau et de terrassons</li>
          <li>Réalisation de solin avec engravure, de noquet</li>
          <li>Fourniture et pose de piques anti-volatiles</li>
        </ul></p>
      </div>
      <div class="imgcard">
        <%= cl_image_tag("Bourdiec06/zinguerie", alt:"zinguerie", class:"imgimgcard") %>
      </div>
    </div>
  </div>
</div>

app/views/pages/mentionslegales.html.erb
o

app/views/pages/services.html.erb
<div class="navspace"></div>
<div class="container">
  <h1><%= t(:nosservices) %></h1>
</div>
<div class="wrapper">
  <div class="container">
    <br>
    <h2><%= t(:plomberie) %></h2>
    <div class="flexbox">
      <div class="textcard">
        <h3>Notre Savoir-Faire:</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, vero aliquam repudiandae labore dignissimos aut consectetur nemo. Accusantium porro alias deleniti sunt animi sequi, eius, nam totam molestiae perferendis iste.</p>
        <br>
        <h3>Nos Services:</h3>
        <p><ul>
          <li>Recherche de fuite</li>
          <li>Dépannage, débouchage</li>
          <li>Réparation et rénovation de salle de bains, sanitaires et cuisines</li>
          <li>Remplacement de cumulus</li>
          <li>Réparation et réfection de canalisation d’eau enterrée, encastrée ou en façade</li>
          <li>Mise aux normes et remplacement de fosse septique</li>
        </ul></p>
      </div>
      <div class="miniflexbox">
        <%= cl_image_tag("Bourdiec06/plomberie.jpg", alt:"plomberie travaux", class:"imgimgcard", style:"width:50vh;") %>
        <%= link_to realisations_path, class:"button2 btn" do %>
          <span><%= t(:photos) %></span>
          <svg>
            <polyline class="o1" points="0 0, 300 0, 300 55, 0 55, 0 0"></polyline>
            <polyline class="o2" points="0 0, 300 0, 300 55, 0 55, 0 0"></polyline>
          </svg>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <br>
  <h2><%= t(:couverture) %></h2>
  <div class="flexbox">
    <div class="textcard">
      <h3>Notre Savoir-Faire:</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, vero aliquam repudiandae labore dignissimos aut consectetur nemo. Accusantium porro alias deleniti sunt animi sequi, eius, nam totam molestiae perferendis iste.</p>
      <br>
      <h3>Nos Services:</h3>
      <p><ul>
        <li>Réfection de toitures en tuiles plates, romanes ou canal</li>
        <li>Recherche de fuite</li>
        <li>Intervention pour réparation en urgence</li>
        <li>Pose de Velux</li>
        <li>Pose d’isolation sous-toiture ou en comble</li>
        <li>Entretien, contrôle et nettoyage annuel de toiture</li>
      </ul></p>
    </div>
      <div class="miniflexbox">
        <%= cl_image_tag("Bourdiec06/toiture2.jpg", alt:"toiture travaux", class:"imgimgcard", style:"width:50vh;") %>
        <%= link_to realisations_path, class:"button2 btn" do %>
          <span><%= t(:photos) %></span>
          <svg>
            <polyline class="o1" points="0 0, 300 0, 300 55, 0 55, 0 0"></polyline>
            <polyline class="o2" points="0 0, 300 0, 300 55, 0 55, 0 0"></polyline>
          </svg>
        <% end %>
      </div>
  </div>
</div>
<div class="wrapper">
  <div class="container">
    <br>
    <h2><%= t(:zinguerie) %></h2>
    <div class="flexbox">
      <div class="textcard">
        <h3>Notre Savoir-Faire:</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, vero aliquam repudiandae labore dignissimos aut consectetur nemo. Accusantium porro alias deleniti sunt animi sequi, eius, nam totam molestiae perferendis iste.</p>
        <br>
        <h3>Nos Services:</h3>
        <p><ul>
          <li>Intervention en urgence sur zinguerie</li>
          <li>Réalisation de tous travaux en zinc et en plomb</li>
          <li>Réfection de gouttière, d'abergement de cheminée, de chéneau et de terrassons</li>
          <li>Réalisation de solin avec engravure, de noquet</li>
          <li>Fourniture et pose de piques anti-volatiles</li>
        </ul></p>
      </div>
      <div class="miniflexbox">
        <%= cl_image_tag("Bourdiec06/banniere.jpg", alt:"zinguerie travaux", class:"imgimgcard", style:"width:50vh;") %>
        <%= link_to realisations_path, class:"button2 btn" do %>
          <span><%= t(:photos) %></span>
          <svg>
            <polyline class="o1" points="0 0, 300 0, 300 55, 0 55, 0 0"></polyline>
            <polyline class="o2" points="0 0, 300 0, 300 55, 0 55, 0 0"></polyline>
          </svg>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <div id="footer">
  <div class="flexbox3" style="justify-content: space-around;">
    <div class="contact-info">
      <h2 style='text-align: center'>BOURDIEC 06</h2>
      <h5 style='text-align: center' ><%= t(:PCZ) %></h5>
      &nbsp;
      <h4><i class="fas fa-map-marker-alt" style="color: #8C1500"></i> 44 rue Longue 06500 Menton</h4>&nbsp;
      <h4><i class="fas fa-envelope-square" style="color: #8C1500"></i> contact@bourdiec06.com</h4> &nbsp;
      <h4><i class="fas fa-phone-square" style="color: #8C1500"></i> 04 93 37 10 19</h4> &nbsp;
      <h4><i class="fas fa-mobile-alt" style="color: #8C1500"></i> 06 14 60 91 04</h4> &nbsp;
    </div>
    <br>
    <div id="map" class="staticmap">

    </div>
  </div>
</div>
</div>

app/views/shared/_footerfooter.html.erb
<div class="footerbis">
  <div class="footerbis-copyright">
    <%= t(:pied) %>
      <%= link_to t(:mentionslegales_link), mentionslegales_path, class:"mentions_link" %>
  </div>
<!--   <div class="footerbis-links">
    <a href="" target="blank"><i class="fab fa-instagram"></i></a>
  </div> -->
</div>

app/views/shared/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h3 style="color:white;"><%= pluralize(@contact.errors.count, "erreur") %> a empêchée votre message de s'envoyer : <% @contact.errors.full_messages.each do |msg| %>
        <%= msg %>
        <br>
      <% end %></h3>
    </div>
  <% end %>

<%= f.label :name, label: t(:votre_nom) %><br />
  <div class="field">
    <%= f.text_field :name, placeholder: t(:obligatoire) %>
  </div>
  <%= f.label :email, label: t(:votre_email) %><br />
  <div class="field">
    <%= f.text_field :email, placeholder: t(:obligatoire) %>
  </div>
    <%= f.label :tel, label: t(:votre_tel) %><br />
  <div class="field">
    <%= f.text_field :tel, placeholder: t(:optionel)%>
  </div>
  <%= f.label :message, label: 'Message ' %><br />
  <div class="field">
    <%= f.text_area :message, placeholder: t(:votre_message), class:'message' %>
  </div>
  <div class="captchadiv">
    <%= recaptcha_tags %>
  </div>

  <label>
    <input type="submit" />
    <div class="button btn">
      <span><%= t(:envoyer) %></span>
      <svg>
        <polyline class="o1" points="0 0, 200 0, 200 55, 0 55, 0 0"></polyline>
        <polyline class="o2" points="0 0, 200 0, 200 55, 0 55, 0 0"></polyline>
      </svg>
    </div>
  </label>


<% end %>

app/views/shared/_navbar.html.erb
    <div class="navbar-tjd">
      <!-- Logo -->
        <%= link_to (image_tag "bourdiec06solo.png", alt:"logo", class:'logonav'), root_path, class:"navbar-tjd-brand hidden-sm" %>
      <!-- Right Navigation -->
      <div class="navbar-tjd-right hidden-xs ">
        <%= link_to t(:home), root_path, class:'navbar-tjd-item navbar-tjd-link' %>
        <%= link_to t(:nosservices), services_path, class:'navbar-tjd-item navbar-tjd-link' %>
        <%= link_to t(:nosrealisations), realisations_path, class:'navbar-tjd-item navbar-tjd-link' %>
        <%= link_to t(:contact), contacts_path, class:'navbar-tjd-item navbar-tjd-link' %>
        <%= link_to (image_tag "FR.png"), { :locale=>'fr' }, class:'navbar-tjd-flag navbar-tjd-link' %>
        <%= link_to (image_tag "GB.png"), { :locale=>'en' }, class:'navbar-tjd-flag navbar-tjd-link' %>
        <%= link_to (image_tag "IT.png"), { :locale=>'it' }, class:'navbar-tjd-flag navbar-tjd-link' %>
      </div>

      <div class="navbar-tjd-right hidden-md hidden-lg hidden-sm ">
        <%= link_to (image_tag "FR.png"), { :locale=>'fr' }, class:'navbar-tjd-flag navbar-tjd-link' %>
        <%= link_to (image_tag "GB.png"), { :locale=>'en' }, class:'navbar-tjd-flag navbar-tjd-link' %>
        <%= link_to (image_tag "IT.png"), { :locale=>'it' }, class:'navbar-tjd-flag navbar-tjd-link' %>
      </div>
      <!-- Dropdown appearing on mobile only -->
      <div class="navbar-tjd-item hidden-md hidden-lg hidden-sm">
        <div class="dropdown">
          <i class="fas fa-bars"class="avatar dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" alt="logo"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-tjd-dropdown-menu" aria-labelledby="dropdownMenu1" >
            <li><%= link_to t(:home), root_path, class:'navbar-tjd-item navbar-tjd-link' %></li>
            <li><%= link_to t(:nosservices), services_path, class:'navbar-tjd-item navbar-tjd-link' %></li>
            <li><%= link_to t(:nosrealisations), realisations_path, class:'navbar-tjd-item navbar-tjd-link' %></li>
            <li> <%= link_to t(:contact), contacts_path, class:'navbar-tjd-item navbar-tjd-link' %></li>
          </ul>
        </div>
      </div>
    </div>